disabled_rules:
  - trailing_whitespace
  - private_over_fileprivate
  - line_length
  - force_cast
  - function_body_length
  - identifier_name
  - cyclomatic_complexity
  - type_body_length
  - file_length
  - force_try
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - MapboxCoreNavigationTests
  - MapboxNavigationTests
  - scripts
  - .build

identifier_name:
  max_length:
    warning: 60
    error: 100
    
nesting:
  type_level:
    warning: 3
    error: 6
  function_level:
    warning: 5
    error: 10