name: iOS

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  format:
    name: Code Style
    runs-on: macos-14
    steps:
    - name: Install tools
      run: brew install swiftlint
      
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Check format
      run: swiftlint lint . --reporter github-actions-logging

  test:
    name: Build and Test
    runs-on: macos-14
    steps:
      - name: Install tools
        run: brew install xcbeautify
        
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
    
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Build
        run: set -o pipefail && xcodebuild build -scheme maplibre-navigation-ios -destination 'platform=iOS Simulator,OS=17.0.1,name=iPhone 15 Pro' | xcbeautify --renderer github-actions

      - name: Test
        run: set -o pipefail && xcodebuild test -scheme maplibre-navigation-ios -destination 'platform=iOS Simulator,OS=17.0.1,name=iPhone 15 Pro' | xcbeautify --renderer github-actions